### ISSUE TITLE
[PE-D][Tester C] Grammatical error in error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-4/tp#100]
![image.png](https://raw.githubusercontent.com/bernicetoh/ped/main/files/c0fae29d-0818-4984-a16b-7ab74f888375.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: bernicetoh/ped#13

**Comment by leeyi45** [comment]
Related to #101
