### ISSUE TITLE
[PE-D][Tester D] Case-sensitive fields

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-4/tp#121]
Suggest to mention that these fields are case sensitive in the user guide

![image.png](https://raw.githubusercontent.com/seadragon2000341/ped/master/files/b7a8a453-b6bc-4848-924f-57d25bec194d.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: seadragon2000341/ped#19

**Comment by leeyi45** [comment]
Related to #95
