### ISSUE TITLE
[PE-D][Tester D] The constraints that only limits to 3 subjects is not well captured

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-4/tp#91]
Subject supported: {Math, Physics, English}
Does not fit well into the target user group, "private tutors managing students" - as there are other tutors that tutors many more subjects other than English, Math and Physics. 

I have labelled this as severity.high, as per the rubrics "A flaw that affects most users and causes major problems for users. i.e., only problems that make the product almost unusable for most users" - it affects most users (private tutors) who tutors other subjects such as Chinese, History, Geog, Chem, Bio... etc and hence "makes the product unusable for most users"

Personally, I do not see a need to have a constraint for subject taught

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: seadragon2000341/ped#6

**Comment by leeyi45** [comment]
Supporting more subjects is part of future development
